services:
  api:
    build: .
    container_name: securetask-api
    ports:
      - "5050:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      JWT_KEY: ${JWT_KEY}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_AUDIENCE: ${JWT_AUDIENCE}
      DATABASE_URL: Host=db;Port=5432;Database=securetaskdb;Username=postgres;Password=123456
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: securetask-postgres
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: securetaskdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
